### ISSUE TITLE
MQTT Authentication

### ISSUE THREAD

**Issue by radimsejk** [EFWob/ESPPubSubClientWrapper#2]
Your library looks good, but sadly I cannot use it because of missing method to set user and password for MQTT authentication. Could you please add it?

**Comment by EFWob** [comment]
Did you use the connect() method? Namely: _connect(const char* id, const char* user, const char* pass);_

Assume you have defined as in the example:

> ESPPubSubClientWrapper client(mqtt_server);

then within setup(), before the first call to _client.loop()_, add the following: 

> client.connect("MyClientName", "user", "password");

The first parameter ("MyClientName") is the id by which the client gets registered by the MQTT-Broker. Can be any random id.

_"user"_ and _"password"_ need to be changed to your MQTT credentials.

This should do the trick I hope...

**Comment by radimsejk** [comment]
Thank you for your advice. I do not know why tried to input user and pass to the object declaration.
